# Generated by Django 5.2.7 on 2025-10-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Your display name (leave blank to use email)",
                max_length=100,
            ),
        ),
    ]
